on:
  push:
    branches: main
jobs:
    deploy_job:
     runs-on: ubuntu-latest
     name: deploy
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: 'chmod -R 777 storage/'
      - name: Install Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Run Laravel migrations
        run: php artisan migrate
      - name: Deploy file
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
         username: 'vorbi@aksasoftware.com'
         server: 'aksasoftware.com'
         port: '21'
         server-dir: '/vorbi/'
         password: 'David@#123'
